# -*- coding: utf-8 -*-
"""Distribucion_probabilidad_continua.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ya4I9rrIcbsK4beuJjoGxOt8q7mkQiZP

## **Distribuciones de probabilidad continuas**

***Presenta: Vanessa Cristell Torres López***
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm, expon, uniform

# Parámetros para las distribuciones
mu = 0            # Media para la distribución Normal
sigma = 1         # Desviación estándar para la distribución Normal
lambda_exp = 1    # Tasa de ocurrencia para la distribución Exponencial
a_uniform = 0     # Límite inferior para la distribución Uniforme Continua
b_uniform = 1     # Límite superior para la distribución Uniforme Continua

# Rango de valores para las variables aleatorias
x_normal = np.linspace(mu - 4*sigma, mu + 4*sigma, 1000)  # Valores para la distribución Normal
x_expon = np.linspace(0, 5, 1000)                        # Valores para la distribución Exponencial
x_uniform = np.linspace(a_uniform, b_uniform, 1000)      # Valores para la distribución Uniforme Continua

# Cálculo de las funciones de densidad de probabilidad (PDF)
pdf_normal = norm.pdf(x_normal, mu, sigma)
pdf_expon = expon.pdf(x_expon, scale=1/lambda_exp)
pdf_uniform = uniform.pdf(x_uniform, a_uniform, b_uniform - a_uniform)

# Creación de subgráficos para cada distribución
fig, axs = plt.subplots(1, 3, figsize=(18, 6))

# Gráfico para la distribución Normal
axs[0].plot(x_normal, pdf_normal, 'b-', label='Normal(μ=0, σ=1)')
axs[0].fill_between(x_normal, pdf_normal, alpha=0.2)
axs[0].set_title('Distribución Normal')
axs[0].set_xlabel('Valor')
axs[0].set_ylabel('Densidad de Probabilidad')
axs[0].legend()

# Gráfico para la distribución Exponencial
axs[1].plot(x_expon, pdf_expon, 'r-', label='Exponencial(λ=1)')
axs[1].fill_between(x_expon, pdf_expon, alpha=0.2)
axs[1].set_title('Distribución Exponencial')
axs[1].set_xlabel('Valor')
axs[1].set_ylabel('Densidad de Probabilidad')
axs[1].legend()

# Gráfico para la distribución Uniforme Continua
axs[2].plot(x_uniform, pdf_uniform, 'g-', label='Uniforme(a=0, b=1)')
axs[2].fill_between(x_uniform, pdf_uniform, alpha=0.2)
axs[2].set_title('Distribución Uniforme Continua')
axs[2].set_xlabel('Valor')
axs[2].set_ylabel('Densidad de Probabilidad')
axs[2].legend()

# Mostrar las gráficas
plt.tight_layout()
plt.show()