# -*- coding: utf-8 -*-
"""MC_orden2_varianza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10p09jrSgCJSE2xcdKZHuBalbfJWb8E03

## **Momento central de orden n**

***Presenta: Vanessa Cristell Torres López***
"""

import numpy as np

# Definir una función para calcular el momento central de orden n
def momento_central(X, n):
    """
    Calcula el momento central de orden n para una variable aleatoria X.
    :param X: Muestra de la variable aleatoria
    :param n: Orden del momento central
    :return: Momento central de orden n
    """
    media = np.mean(X)
    return np.mean((X - media)**n)

# Generar una muestra aleatoria de una distribución normal
np.random.seed(42)  # Para reproducibilidad
X = np.random.normal(loc=0, scale=1, size=1000)

# Calcular el momento central de orden n (por ejemplo, n = 2)
n = 2
momento_orden_n = momento_central(X, n)

# Verificar si se cumple para k = 2 (esto es, si el resultado es igual a la varianza)
varianza = np.var(X)

momento_orden_n, varianza