# -*- coding: utf-8 -*-
"""Regla_multiplicacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTWER-XtWvU8MfUNaLWfrr2GNeZYtu6e

## **Regla de la multiplicacion**

***Presenta: Vanessa Cristell Torres López***
"""

# Definimos el espacio muestral
Omega = {1, 2, 3, 4, 5, 6}

# Definimos una función de probabilidad P para eventos en el espacio muestral
def P(event):
    probabilities = {
        frozenset(): 0,               # P(conjunto vacío) = 0
        frozenset({1}): 1/6,          # P({1}) = 1/6
        frozenset({2}): 1/6,          # P({2}) = 1/6
        frozenset({3}): 1/6,          # P({3}) = 1/6
        frozenset({4}): 1/6,          # P({4}) = 1/6
        frozenset({5}): 1/6,          # P({5}) = 1/6
        frozenset({6}): 1/6,          # P({6}) = 1/6
        frozenset({1, 2}): 1/3,      # P({1, 2}) = 1/3 (ejemplo)
        frozenset({3, 4}): 1/3,      # P({3, 4}) = 1/3 (ejemplo)
        frozenset({5, 6}): 1/3,      # P({5, 6}) = 1/3 (ejemplo)
        frozenset(Omega): 1          # P(Omega) = 1
    }
    return probabilities.get(frozenset(event), 0)

# Define los eventos
A = {1, 2}
B = {2, 3}

# Calculamos las probabilidades
P_A = P(A)
P_B = P(B)
P_A_inter_B = P(A.intersection(B))

# Supongamos que la probabilidad condicional de A dado B
P_A_given_B = P_A_inter_B / P_B

# Verificamos la regla de la multiplicación
calculated_intersection = P_A_given_B * P_B

# Resultados
print(f"P(A) = {P_A}")
print(f"P(B) = {P_B}")
print(f"P(A ∩ B) = {P_A_inter_B}")
print(f"P(A | B) = {P_A_given_B}")
print(f"P(A ∩ B) (calculado usando la regla de multiplicación) = {calculated_intersection}")

# Verificar si coincide con la probabilidad de la intersección
if calculated_intersection == P_A_inter_B:
    print("La regla de la multiplicación se cumple.")
else:
    print("La regla de la multiplicación no se cumple.")