# -*- coding: utf-8 -*-
"""Valor_Esperado.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SZ79hn1GxluWk0I7yLWmQvs_9Rgs2G6o

## **Cálculo del valor esperado comparado con la media aritmética**

***Presenta: Vanessa Cristell Torres López***
"""

import numpy as np
import scipy.stats as stats

def valor_esperado_simetrico(mu, sigma):
    """
    Calcula el valor esperado de una distribución normal simétrica.

    Parámetros:
    mu -- Media de la distribución normal
    sigma -- Desviación estándar de la distribución normal

    Retorna:
    valor esperado de la distribución normal
    """
    return mu

def valor_esperado_asimetrico(lam):
    """
    Calcula el valor esperado de una distribución exponencial asimétrica.

    Parámetros:
    lam -- Tasa de la distribución exponencial (1 / media)

    Retorna:
    valor esperado de la distribución exponencial
    """
    return 1 / lam

def media_aritmetica(datos):
    """
    Calcula la media aritmética de un conjunto de datos.

    Parámetros:
    datos -- Lista o array de valores

    Retorna:
    media aritmética de los datos
    """
    return np.mean(datos)

# Ejemplo de uso

# Parámetros para la distribución normal
mu = 0       # Media
sigma = 1    # Desviación estándar

# Parámetro para la distribución exponencial
lam = 1      # Tasa

# Datos de ejemplo para calcular la media aritmética
datos = np.random.normal(mu, sigma, 1000)

# Calcular valores esperados
valor_esperado_normal = valor_esperado_simetrico(mu, sigma)
valor_esperado_exponencial = valor_esperado_asimetrico(lam)

# Calcular media aritmética de los datos
media_datos = media_aritmetica(datos)

print(f"Valor esperado de la distribución normal: {valor_esperado_normal}")
print(f"Valor esperado de la distribución exponencial: {valor_esperado_exponencial}")
print(f"Media aritmética de los datos: {media_datos}")